spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/openpenpal
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.openpenpal.admin: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

admin:
  default-password: admin123