CREATE UNIQUE INDEX ai_config_histories_pkey ON public.ai_config_histories USING btree (id);
CREATE UNIQUE INDEX ai_configs_pkey ON public.ai_configs USING btree (id);
CREATE INDEX idx_ai_configs_category ON public.ai_configs USING btree (category);
CREATE INDEX idx_ai_configs_config_type ON public.ai_configs USING btree (config_type);
CREATE INDEX idx_ai_configs_is_active ON public.ai_configs USING btree (is_active);
CREATE UNIQUE INDEX idx_ai_configs_provider ON public.ai_configs USING btree (provider);
CREATE UNIQUE INDEX ai_content_templates_pkey ON public.ai_content_templates USING btree (id);
CREATE INDEX idx_ai_content_templates_category ON public.ai_content_templates USING btree (category);
CREATE INDEX idx_ai_content_templates_is_active ON public.ai_content_templates USING btree (is_active);
CREATE INDEX idx_ai_content_templates_template_type ON public.ai_content_templates USING btree (template_type);
CREATE UNIQUE INDEX ai_curations_pkey ON public.ai_curations USING btree (id);
CREATE INDEX idx_ai_curations_exhibition_id ON public.ai_curations USING btree (exhibition_id);
CREATE INDEX idx_ai_curations_letter_id ON public.ai_curations USING btree (letter_id);
CREATE UNIQUE INDEX ai_inspirations_pkey ON public.ai_inspirations USING btree (id);
CREATE INDEX idx_ai_inspirations_user_id ON public.ai_inspirations USING btree (user_id);
CREATE UNIQUE INDEX ai_matches_pkey ON public.ai_matches USING btree (id);
CREATE INDEX idx_ai_matches_letter_id ON public.ai_matches USING btree (letter_id);
CREATE INDEX idx_ai_matches_matched_user_id ON public.ai_matches USING btree (matched_user_id);
CREATE UNIQUE INDEX ai_replies_pkey ON public.ai_replies USING btree (id);
CREATE INDEX idx_ai_replies_original_letter_id ON public.ai_replies USING btree (original_letter_id);
CREATE INDEX idx_ai_replies_reply_letter_id ON public.ai_replies USING btree (reply_letter_id);
CREATE UNIQUE INDEX ai_reply_advices_pkey ON public.ai_reply_advices USING btree (id);
CREATE INDEX idx_ai_reply_advices_letter_id ON public.ai_reply_advices USING btree (letter_id);
CREATE INDEX idx_ai_reply_advices_user_id ON public.ai_reply_advices USING btree (user_id);
CREATE UNIQUE INDEX ai_usage_logs_pkey ON public.ai_usage_logs USING btree (id);
CREATE INDEX idx_ai_usage_logs_task_id ON public.ai_usage_logs USING btree (task_id);
CREATE INDEX idx_ai_usage_logs_user_id ON public.ai_usage_logs USING btree (user_id);
CREATE UNIQUE INDEX analytics_metrics_pkey ON public.analytics_metrics USING btree (id);
CREATE INDEX idx_analytics_metrics_metric_type ON public.analytics_metrics USING btree (metric_type);
CREATE INDEX idx_analytics_metrics_timestamp ON public.analytics_metrics USING btree ("timestamp");
CREATE UNIQUE INDEX analytics_reports_pkey ON public.analytics_reports USING btree (id);
CREATE UNIQUE INDEX batch_analytics_batch_id_key ON public.batch_analytics USING btree (batch_id);
CREATE UNIQUE INDEX batch_analytics_pkey ON public.batch_analytics USING btree (id);
CREATE INDEX idx_batch_analytics_batch_id ON public.batch_analytics USING btree (batch_id);
CREATE INDEX idx_batch_analytics_updated_at ON public.batch_analytics USING btree (updated_at);
CREATE UNIQUE INDEX batch_distribution_records_pkey ON public.batch_distribution_records USING btree (id);
CREATE INDEX idx_distribution_batch_id ON public.batch_distribution_records USING btree (batch_id);
CREATE INDEX idx_distribution_by ON public.batch_distribution_records USING btree (distributed_by);
CREATE INDEX idx_distribution_created_at ON public.batch_distribution_records USING btree (created_at);
CREATE INDEX idx_distribution_to ON public.batch_distribution_records USING btree (distributed_to);
CREATE UNIQUE INDEX batch_events_pkey ON public.batch_events USING btree (id);
CREATE INDEX idx_batch_events_batch_id ON public.batch_events USING btree (batch_id);
CREATE INDEX idx_batch_events_created_at ON public.batch_events USING btree (created_at);
CREATE INDEX idx_batch_events_event_type ON public.batch_events USING btree (event_type);
CREATE INDEX idx_batch_events_user_id ON public.batch_events USING btree (user_id);
CREATE UNIQUE INDEX batch_health_metrics_pkey ON public.batch_health_metrics USING btree (id);
CREATE INDEX idx_health_metrics_batch_id ON public.batch_health_metrics USING btree (batch_id);
CREATE INDEX idx_health_metrics_metric_type ON public.batch_health_metrics USING btree (metric_type);
CREATE INDEX idx_health_metrics_recorded_at ON public.batch_health_metrics USING btree (recorded_at);
CREATE UNIQUE INDEX batch_milestones_pkey ON public.batch_milestones USING btree (id);
CREATE INDEX idx_batch_milestones_batch_id ON public.batch_milestones USING btree (batch_id);
CREATE UNIQUE INDEX uk_batch_milestone ON public.batch_milestones USING btree (batch_id, milestone);
CREATE UNIQUE INDEX batch_notification_history_pkey ON public.batch_notification_history USING btree (id);
CREATE INDEX idx_batch_notification_batch_id ON public.batch_notification_history USING btree (batch_id);
CREATE INDEX idx_batch_notification_created_at ON public.batch_notification_history USING btree (created_at);
CREATE INDEX idx_batch_notification_user_id ON public.batch_notification_history USING btree (user_id);
CREATE UNIQUE INDEX batch_permissions_pkey ON public.batch_permissions USING btree (id);
CREATE INDEX idx_batch_permissions_batch_id ON public.batch_permissions USING btree (batch_id);
CREATE INDEX idx_batch_permissions_user_id ON public.batch_permissions USING btree (user_id);
CREATE UNIQUE INDEX uk_batch_user_permission ON public.batch_permissions USING btree (batch_id, user_id, permission_type);
CREATE UNIQUE INDEX cart_items_pkey ON public.cart_items USING btree (id);
CREATE INDEX idx_cart_items_cart_id ON public.cart_items USING btree (cart_id);
CREATE INDEX idx_cart_items_product_id ON public.cart_items USING btree (product_id);
CREATE UNIQUE INDEX carts_pkey ON public.carts USING btree (id);
CREATE INDEX idx_carts_user_id ON public.carts USING btree (user_id);
CREATE UNIQUE INDEX cloud_letters_pkey ON public.cloud_letters USING btree (id);
CREATE INDEX idx_cloud_letters_persona_id ON public.cloud_letters USING btree (persona_id);
CREATE INDEX idx_cloud_letters_user_id ON public.cloud_letters USING btree (user_id);
CREATE UNIQUE INDEX cloud_personas_pkey ON public.cloud_personas USING btree (id);
CREATE INDEX idx_cloud_personas_user_id ON public.cloud_personas USING btree (user_id);
CREATE UNIQUE INDEX comment_likes_pkey ON public.comment_likes USING btree (id);
CREATE INDEX idx_comment_likes_comment_id ON public.comment_likes USING btree (comment_id);
CREATE INDEX idx_comment_likes_deleted_at ON public.comment_likes USING btree (deleted_at);
CREATE INDEX idx_comment_likes_user_id ON public.comment_likes USING btree (user_id);
CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);
CREATE INDEX idx_comments_deleted_at ON public.comments USING btree (deleted_at);
CREATE INDEX idx_comments_letter_id ON public.comments USING btree (letter_id);
CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);
CREATE INDEX idx_comments_user_id ON public.comments USING btree (user_id);
CREATE UNIQUE INDEX content_violation_records_pkey ON public.content_violation_records USING btree (id);
CREATE INDEX idx_content_violation_records_content_id ON public.content_violation_records USING btree (content_id);
CREATE INDEX idx_content_violation_records_user_id ON public.content_violation_records USING btree (user_id);
CREATE UNIQUE INDEX courier_badge_earneds_pkey ON public.courier_badge_earneds USING btree (id);
CREATE INDEX idx_courier_badge_earneds_courier_id ON public.courier_badge_earneds USING btree (courier_id);
CREATE UNIQUE INDEX courier_badges_pkey ON public.courier_badges USING btree (id);
CREATE UNIQUE INDEX uni_courier_badges_code ON public.courier_badges USING btree (code);
CREATE UNIQUE INDEX courier_growth_paths_pkey ON public.courier_growth_paths USING btree (id);
CREATE UNIQUE INDEX courier_incentives_pkey ON public.courier_incentives USING btree (id);
CREATE UNIQUE INDEX courier_level_models_pkey ON public.courier_level_models USING btree (id);
CREATE UNIQUE INDEX uni_courier_level_models_level ON public.courier_level_models USING btree (level);
CREATE UNIQUE INDEX courier_permission_models_pkey ON public.courier_permission_models USING btree (id);
CREATE UNIQUE INDEX uni_courier_permission_models_permission ON public.courier_permission_models USING btree (permission);
CREATE UNIQUE INDEX courier_points_pkey ON public.courier_points USING btree (id);
CREATE INDEX idx_courier_points_courier_id ON public.courier_points USING btree (courier_id);
CREATE UNIQUE INDEX courier_points_histories_pkey ON public.courier_points_histories USING btree (id);
CREATE INDEX idx_courier_points_histories_courier_id ON public.courier_points_histories USING btree (courier_id);
CREATE INDEX idx_courier_points_histories_task_id ON public.courier_points_histories USING btree (task_id);
CREATE UNIQUE INDEX courier_points_transactions_pkey ON public.courier_points_transactions USING btree (id);
CREATE INDEX idx_courier_points_transactions_courier_id ON public.courier_points_transactions USING btree (courier_id);
CREATE UNIQUE INDEX courier_rankings_pkey ON public.courier_rankings USING btree (id);
CREATE INDEX idx_courier_rankings_courier_id ON public.courier_rankings USING btree (courier_id);
CREATE UNIQUE INDEX courier_statistics_pkey ON public.courier_statistics USING btree (id);
CREATE UNIQUE INDEX idx_courier_date ON public.courier_statistics USING btree (courier_id, date);
CREATE UNIQUE INDEX courier_tasks_pkey ON public.courier_tasks USING btree (id);
CREATE INDEX idx_courier_tasks_courier_id ON public.courier_tasks USING btree (courier_id);
CREATE INDEX idx_courier_tasks_courier_status_priority ON public.courier_tasks USING btree (courier_id, status, priority, created_at DESC);
CREATE INDEX idx_courier_tasks_current_op_code ON public.courier_tasks USING btree (current_op_code);
CREATE INDEX idx_courier_tasks_current_opcode_status ON public.courier_tasks USING btree (current_op_code, status) WHERE ((current_op_code)::text <> ''::text);
CREATE INDEX idx_courier_tasks_deadline_status ON public.courier_tasks USING btree (deadline, status) WHERE (deadline IS NOT NULL);
CREATE INDEX idx_courier_tasks_delivery_op ON public.courier_tasks USING btree (delivery_op_code);
CREATE INDEX idx_courier_tasks_delivery_op_code ON public.courier_tasks USING btree (delivery_op_code);
CREATE INDEX idx_courier_tasks_geo_routing ON public.courier_tasks USING btree (pickup_op_code, delivery_op_code, status, priority) WHERE (((pickup_op_code)::text <> ''::text) AND ((delivery_op_code)::text <> ''::text));
CREATE INDEX idx_courier_tasks_letter_code ON public.courier_tasks USING btree (letter_code);
CREATE INDEX idx_courier_tasks_pickup_delivery_opcode ON public.courier_tasks USING btree (pickup_op_code, delivery_op_code) WHERE (((pickup_op_code)::text <> ''::text) AND ((delivery_op_code)::text <> ''::text));
CREATE INDEX idx_courier_tasks_pickup_op ON public.courier_tasks USING btree (pickup_op_code);
CREATE INDEX idx_courier_tasks_pickup_op_code ON public.courier_tasks USING btree (pickup_op_code);
CREATE UNIQUE INDEX courier_zones_pkey ON public.courier_zones USING btree (id);
CREATE INDEX idx_courier_zones_courier_id ON public.courier_zones USING btree (courier_id);
CREATE UNIQUE INDEX couriers_pkey ON public.couriers USING btree (id);
CREATE INDEX idx_couriers_active_hierarchy ON public.couriers USING btree (parent_id, level, created_at DESC) WHERE (((status)::text = 'approved'::text) AND (deleted_at IS NULL));
CREATE INDEX idx_couriers_created_by_id ON public.couriers USING btree (created_by_id);
CREATE INDEX idx_couriers_created_by_time ON public.couriers USING btree (created_by_id, created_at DESC) WHERE (created_by_id IS NOT NULL);
CREATE INDEX idx_couriers_deleted_at ON public.couriers USING btree (deleted_at);
CREATE INDEX idx_couriers_level_zone_active ON public.couriers USING btree (level, zone_code, deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_couriers_managed_op_code_prefix ON public.couriers USING btree (managed_op_code_prefix);
CREATE INDEX idx_couriers_managed_prefix ON public.couriers USING btree (managed_op_code_prefix);
CREATE INDEX idx_couriers_managed_prefix_level ON public.couriers USING btree (managed_op_code_prefix, level) WHERE ((managed_op_code_prefix)::text <> ''::text);
CREATE INDEX idx_couriers_parent_id ON public.couriers USING btree (parent_id);
CREATE INDEX idx_couriers_parent_level ON public.couriers USING btree (parent_id, level) WHERE (parent_id IS NOT NULL);
CREATE INDEX idx_couriers_status_level ON public.couriers USING btree (status, level, deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_couriers_user_id ON public.couriers USING btree (user_id);
CREATE INDEX idx_couriers_zone_code ON public.couriers USING btree (zone_code);
CREATE UNIQUE INDEX credit_activities_pkey ON public.credit_activities USING btree (id);
CREATE INDEX idx_activities_created_at ON public.credit_activities USING btree (created_at);
CREATE INDEX idx_activities_end_time ON public.credit_activities USING btree (end_time);
CREATE INDEX idx_activities_priority ON public.credit_activities USING btree (priority);
CREATE INDEX idx_activities_start_time ON public.credit_activities USING btree (start_time);
CREATE INDEX idx_activities_status ON public.credit_activities USING btree (status);
CREATE INDEX idx_activities_target_audience ON public.credit_activities USING btree (target_audience_type);
CREATE INDEX idx_activities_type ON public.credit_activities USING btree (activity_type);
CREATE UNIQUE INDEX credit_activity_participations_pkey ON public.credit_activity_participations USING btree (id);
CREATE INDEX idx_participations_activity_id ON public.credit_activity_participations USING btree (activity_id);
CREATE INDEX idx_participations_activity_user ON public.credit_activity_participations USING btree (activity_id, user_id);
CREATE INDEX idx_participations_completion_time ON public.credit_activity_participations USING btree (completion_time);
CREATE INDEX idx_participations_is_rewarded ON public.credit_activity_participations USING btree (is_rewarded);
CREATE INDEX idx_participations_participation_time ON public.credit_activity_participations USING btree (participation_time);
CREATE INDEX idx_participations_status ON public.credit_activity_participations USING btree (completion_status);
CREATE INDEX idx_participations_unique_activity_user_time ON public.credit_activity_participations USING btree (activity_id, user_id, date(participation_time));
CREATE INDEX idx_participations_user_id ON public.credit_activity_participations USING btree (user_id);
CREATE UNIQUE INDEX credit_activity_rewards_pkey ON public.credit_activity_rewards USING btree (id);
CREATE INDEX idx_rewards_activity_id ON public.credit_activity_rewards USING btree (activity_id);
CREATE INDEX idx_rewards_activity_user ON public.credit_activity_rewards USING btree (activity_id, user_id);
CREATE INDEX idx_rewards_awarded_at ON public.credit_activity_rewards USING btree (awarded_at);
CREATE INDEX idx_rewards_participation_id ON public.credit_activity_rewards USING btree (participation_id);
CREATE INDEX idx_rewards_status ON public.credit_activity_rewards USING btree (status);
CREATE INDEX idx_rewards_transaction_id ON public.credit_activity_rewards USING btree (transaction_id);
CREATE INDEX idx_rewards_user_id ON public.credit_activity_rewards USING btree (user_id);
CREATE UNIQUE INDEX credit_activity_rules_pkey ON public.credit_activity_rules USING btree (id);
CREATE INDEX idx_activity_rules_activity_id ON public.credit_activity_rules USING btree (activity_id);
CREATE INDEX idx_activity_rules_is_active ON public.credit_activity_rules USING btree (is_active);
CREATE INDEX idx_activity_rules_priority ON public.credit_activity_rules USING btree (priority);
CREATE INDEX idx_activity_rules_type ON public.credit_activity_rules USING btree (rule_type);
CREATE UNIQUE INDEX credit_activity_schedules_pkey ON public.credit_activity_schedules USING btree (id);
CREATE INDEX idx_activity_schedules_activity_id ON public.credit_activity_schedules USING btree (activity_id);
CREATE INDEX idx_activity_schedules_last_execution ON public.credit_activity_schedules USING btree (last_execution_time);
CREATE INDEX idx_activity_schedules_next_execution ON public.credit_activity_schedules USING btree (next_execution_time);
CREATE INDEX idx_activity_schedules_schedule_time ON public.credit_activity_schedules USING btree (schedule_time);
CREATE INDEX idx_activity_schedules_status ON public.credit_activity_schedules USING btree (status);
CREATE INDEX idx_activity_schedules_type ON public.credit_activity_schedules USING btree (schedule_type);
CREATE UNIQUE INDEX credit_activity_target_audiences_pkey ON public.credit_activity_target_audiences USING btree (id);
CREATE INDEX idx_target_audiences_activity_id ON public.credit_activity_target_audiences USING btree (activity_id);
CREATE INDEX idx_target_audiences_rule ON public.credit_activity_target_audiences USING btree (inclusion_rule);
CREATE INDEX idx_target_audiences_type ON public.credit_activity_target_audiences USING btree (target_type);
CREATE INDEX idx_target_audiences_value ON public.credit_activity_target_audiences USING btree (target_value);
CREATE UNIQUE INDEX uk_target_audiences ON public.credit_activity_target_audiences USING btree (activity_id, target_type, target_value);
CREATE UNIQUE INDEX credit_activity_templates_pkey ON public.credit_activity_templates USING btree (id);
CREATE INDEX idx_activity_templates_category ON public.credit_activity_templates USING btree (category);
CREATE INDEX idx_activity_templates_created_at ON public.credit_activity_templates USING btree (created_at);
CREATE INDEX idx_activity_templates_is_public ON public.credit_activity_templates USING btree (is_public);
CREATE INDEX idx_activity_templates_type ON public.credit_activity_templates USING btree (template_type);
CREATE INDEX idx_activity_templates_usage_count ON public.credit_activity_templates USING btree (usage_count);
CREATE UNIQUE INDEX credit_cart_items_pkey ON public.credit_cart_items USING btree (id);
CREATE INDEX idx_credit_cart_items_cart_id ON public.credit_cart_items USING btree (cart_id);
CREATE INDEX idx_credit_cart_items_product_id ON public.credit_cart_items USING btree (product_id);
CREATE UNIQUE INDEX credit_carts_pkey ON public.credit_carts USING btree (id);
CREATE INDEX idx_credit_carts_user_id ON public.credit_carts USING btree (user_id);
CREATE UNIQUE INDEX credit_expiration_batches_pkey ON public.credit_expiration_batches USING btree (id);
CREATE INDEX idx_expiration_batches_batch_date ON public.credit_expiration_batches USING btree (batch_date);
CREATE INDEX idx_expiration_batches_completed_at ON public.credit_expiration_batches USING btree (completed_at);
CREATE INDEX idx_expiration_batches_started_at ON public.credit_expiration_batches USING btree (started_at);
CREATE INDEX idx_expiration_batches_status ON public.credit_expiration_batches USING btree (status);
CREATE UNIQUE INDEX credit_expiration_logs_pkey ON public.credit_expiration_logs USING btree (id);
CREATE INDEX idx_expiration_logs_batch_id ON public.credit_expiration_logs USING btree (batch_id);
CREATE INDEX idx_expiration_logs_expired_at ON public.credit_expiration_logs USING btree (expired_at);
CREATE INDEX idx_expiration_logs_notification_sent ON public.credit_expiration_logs USING btree (notification_sent);
CREATE INDEX idx_expiration_logs_recovery_deadline ON public.credit_expiration_logs USING btree (recovery_deadline);
CREATE INDEX idx_expiration_logs_transaction_id ON public.credit_expiration_logs USING btree (transaction_id);
CREATE INDEX idx_expiration_logs_user_id ON public.credit_expiration_logs USING btree (user_id);
CREATE UNIQUE INDEX credit_expiration_notifications_pkey ON public.credit_expiration_notifications USING btree (id);
CREATE INDEX idx_expiration_notifications_expiring_date ON public.credit_expiration_notifications USING btree (expiring_date);
CREATE INDEX idx_expiration_notifications_retry_count ON public.credit_expiration_notifications USING btree (retry_count);
CREATE INDEX idx_expiration_notifications_sent_at ON public.credit_expiration_notifications USING btree (sent_at);
CREATE INDEX idx_expiration_notifications_status ON public.credit_expiration_notifications USING btree (status);
CREATE INDEX idx_expiration_notifications_type ON public.credit_expiration_notifications USING btree (notification_type);
CREATE INDEX idx_expiration_notifications_user_id ON public.credit_expiration_notifications USING btree (user_id);
CREATE UNIQUE INDEX credit_expiration_rules_pkey ON public.credit_expiration_rules USING btree (id);
CREATE INDEX idx_expiration_rules_credit_type ON public.credit_expiration_rules USING btree (credit_type);
CREATE INDEX idx_expiration_rules_expiration_days ON public.credit_expiration_rules USING btree (expiration_days);
CREATE INDEX idx_expiration_rules_is_active ON public.credit_expiration_rules USING btree (is_active);
CREATE UNIQUE INDEX credit_limit_rules_pkey ON public.credit_limit_rules USING btree (id);
CREATE INDEX idx_credit_limit_rules_action_enabled ON public.credit_limit_rules USING btree (action_type, enabled);
CREATE INDEX idx_credit_limit_rules_action_type ON public.credit_limit_rules USING btree (action_type);
CREATE INDEX idx_credit_limit_rules_priority ON public.credit_limit_rules USING btree (priority, enabled);
CREATE UNIQUE INDEX credit_redemptions_pkey ON public.credit_redemptions USING btree (id);
CREATE INDEX idx_credit_redemptions_created_at ON public.credit_redemptions USING btree (created_at DESC);
CREATE INDEX idx_credit_redemptions_product_id ON public.credit_redemptions USING btree (product_id);
CREATE INDEX idx_credit_redemptions_redemption_no ON public.credit_redemptions USING btree (redemption_no);
CREATE INDEX idx_credit_redemptions_status ON public.credit_redemptions USING btree (status);
CREATE INDEX idx_credit_redemptions_user_id ON public.credit_redemptions USING btree (user_id);
CREATE INDEX idx_credit_redemptions_user_status ON public.credit_redemptions USING btree (user_id, status);
CREATE UNIQUE INDEX uni_credit_redemptions_redemption_no ON public.credit_redemptions USING btree (redemption_no);
CREATE UNIQUE INDEX credit_risk_users_pkey ON public.credit_risk_users USING btree (user_id);
CREATE INDEX idx_credit_risk_users_blocked ON public.credit_risk_users USING btree (blocked_until) WHERE (blocked_until IS NOT NULL);
CREATE INDEX idx_credit_risk_users_level_score ON public.credit_risk_users USING btree (risk_level, risk_score);
CREATE UNIQUE INDEX credit_rules_pkey ON public.credit_rules USING btree (id);
CREATE UNIQUE INDEX idx_credit_rules_action ON public.credit_rules USING btree (action);
CREATE UNIQUE INDEX credit_shop_categories_pkey ON public.credit_shop_categories USING btree (id);
CREATE INDEX idx_credit_shop_categories_active_sort ON public.credit_shop_categories USING btree (is_active, sort_order);
CREATE INDEX idx_credit_shop_categories_parent_id ON public.credit_shop_categories USING btree (parent_id);
CREATE UNIQUE INDEX credit_shop_configs_pkey ON public.credit_shop_configs USING btree (id);
CREATE INDEX idx_credit_shop_configs_category ON public.credit_shop_configs USING btree (category);
CREATE UNIQUE INDEX idx_credit_shop_configs_key ON public.credit_shop_configs USING btree (key);
CREATE UNIQUE INDEX credit_shop_products_pkey ON public.credit_shop_products USING btree (id);
CREATE INDEX idx_credit_shop_products_category ON public.credit_shop_products USING btree (category);
CREATE INDEX idx_credit_shop_products_deleted ON public.credit_shop_products USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);
CREATE INDEX idx_credit_shop_products_deleted_at ON public.credit_shop_products USING btree (deleted_at);
CREATE INDEX idx_credit_shop_products_featured ON public.credit_shop_products USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX idx_credit_shop_products_price ON public.credit_shop_products USING btree (credit_price);
CREATE INDEX idx_credit_shop_products_priority ON public.credit_shop_products USING btree (priority DESC, created_at DESC);
CREATE INDEX idx_credit_shop_products_status ON public.credit_shop_products USING btree (status);
CREATE INDEX idx_credit_shop_products_stock ON public.credit_shop_products USING btree (stock) WHERE (stock > 0);
CREATE INDEX idx_credit_shop_products_type ON public.credit_shop_products USING btree (product_type);
CREATE INDEX idx_credit_shop_products_valid_period ON public.credit_shop_products USING btree (valid_from, valid_to);
CREATE UNIQUE INDEX credit_transactions_pkey ON public.credit_transactions USING btree (id);
CREATE INDEX idx_credit_transactions_expired_at ON public.credit_transactions USING btree (expired_at) WHERE (expired_at IS NOT NULL);
CREATE INDEX idx_credit_transactions_expires_at ON public.credit_transactions USING btree (expires_at);
CREATE INDEX idx_credit_transactions_is_expired ON public.credit_transactions USING btree (is_expired);
CREATE INDEX idx_credit_transactions_user_id ON public.credit_transactions USING btree (user_id);
CREATE UNIQUE INDEX credit_transfer_limits_pkey ON public.credit_transfer_limits USING btree (id);
CREATE INDEX idx_transfer_limits_blocked_until ON public.credit_transfer_limits USING btree (blocked_until);
CREATE INDEX idx_transfer_limits_is_blocked ON public.credit_transfer_limits USING btree (is_blocked);
CREATE INDEX idx_transfer_limits_reset_at ON public.credit_transfer_limits USING btree (reset_at);
CREATE INDEX idx_transfer_limits_type ON public.credit_transfer_limits USING btree (limit_type);
CREATE INDEX idx_transfer_limits_user_id ON public.credit_transfer_limits USING btree (user_id);
CREATE UNIQUE INDEX uk_transfer_limit_user_type ON public.credit_transfer_limits USING btree (user_id, limit_type);
CREATE UNIQUE INDEX credit_transfer_notifications_pkey ON public.credit_transfer_notifications USING btree (id);
CREATE INDEX idx_transfer_notifications_delivery_method ON public.credit_transfer_notifications USING btree (delivery_method);
CREATE INDEX idx_transfer_notifications_sent_at ON public.credit_transfer_notifications USING btree (sent_at);
CREATE INDEX idx_transfer_notifications_status ON public.credit_transfer_notifications USING btree (status);
CREATE INDEX idx_transfer_notifications_transfer_id ON public.credit_transfer_notifications USING btree (transfer_id);
CREATE INDEX idx_transfer_notifications_type ON public.credit_transfer_notifications USING btree (notification_type);
CREATE INDEX idx_transfer_notifications_user_id ON public.credit_transfer_notifications USING btree (user_id);
CREATE UNIQUE INDEX credit_transfer_rules_pkey ON public.credit_transfer_rules USING btree (id);
CREATE INDEX idx_transfer_rules_is_active ON public.credit_transfer_rules USING btree (is_active);
CREATE INDEX idx_transfer_rules_priority ON public.credit_transfer_rules USING btree (priority);
CREATE INDEX idx_transfer_rules_requires_approval ON public.credit_transfer_rules USING btree (requires_approval);
CREATE INDEX idx_transfer_rules_type ON public.credit_transfer_rules USING btree (rule_type);
CREATE UNIQUE INDEX credit_transfers_pkey ON public.credit_transfers USING btree (id);
CREATE INDEX idx_transfers_approved_at ON public.credit_transfers USING btree (approved_at);
CREATE INDEX idx_transfers_completed_at ON public.credit_transfers USING btree (completed_at);
CREATE INDEX idx_transfers_created_at ON public.credit_transfers USING btree (created_at);
CREATE INDEX idx_transfers_expires_at ON public.credit_transfers USING btree (expires_at);
CREATE INDEX idx_transfers_from_user_id ON public.credit_transfers USING btree (from_user_id);
CREATE INDEX idx_transfers_reference_id ON public.credit_transfers USING btree (reference_id);
CREATE INDEX idx_transfers_status ON public.credit_transfers USING btree (status);
CREATE INDEX idx_transfers_to_user_id ON public.credit_transfers USING btree (to_user_id);
CREATE INDEX idx_transfers_type ON public.credit_transfers USING btree (transfer_type);
CREATE UNIQUE INDEX delay_queue_records_pkey ON public.delay_queue_records USING btree (id);
CREATE INDEX idx_delay_queue_delayed_until ON public.delay_queue_records USING btree (delayed_until);
CREATE INDEX idx_delay_queue_status ON public.delay_queue_records USING btree (status);
CREATE INDEX idx_delay_queue_type ON public.delay_queue_records USING btree (type);
CREATE UNIQUE INDEX distribution_plans_pkey ON public.distribution_plans USING btree (id);
CREATE INDEX idx_distribution_plans_batch_id ON public.distribution_plans USING btree (batch_id);
CREATE INDEX idx_distribution_plans_created_by ON public.distribution_plans USING btree (created_by);
CREATE UNIQUE INDEX email_logs_pkey ON public.email_logs USING btree (id);
CREATE INDEX idx_email_logs_notification_id ON public.email_logs USING btree (notification_id);
CREATE INDEX idx_email_logs_user_id ON public.email_logs USING btree (user_id);
CREATE UNIQUE INDEX email_templates_pkey ON public.email_templates USING btree (id);
CREATE UNIQUE INDEX idx_email_templates_name ON public.email_templates USING btree (name);
CREATE UNIQUE INDEX envelope_designs_pkey ON public.envelope_designs USING btree (id);
CREATE INDEX idx_envelope_designs_creator_id ON public.envelope_designs USING btree (creator_id);
CREATE INDEX idx_envelope_designs_deleted_at ON public.envelope_designs USING btree (deleted_at);
CREATE INDEX idx_envelope_designs_supported_op_code_prefix ON public.envelope_designs USING btree (supported_op_code_prefix);
CREATE UNIQUE INDEX envelope_orders_pkey ON public.envelope_orders USING btree (id);
CREATE UNIQUE INDEX envelope_votes_pkey ON public.envelope_votes USING btree (id);
CREATE UNIQUE INDEX envelopes_pkey ON public.envelopes USING btree (id);
CREATE INDEX idx_envelopes_letter_id ON public.envelopes USING btree (letter_id);
CREATE INDEX idx_envelopes_recipient_op_code ON public.envelopes USING btree (recipient_op_code);
CREATE INDEX idx_envelopes_sender_op_code ON public.envelopes USING btree (sender_op_code);
CREATE UNIQUE INDEX uni_envelopes_barcode_id ON public.envelopes USING btree (barcode_id);
CREATE UNIQUE INDEX follow_activities_pkey ON public.follow_activities USING btree (id);
CREATE INDEX idx_follow_activities_actor ON public.follow_activities USING btree (actor_id);
CREATE INDEX idx_follow_activities_created ON public.follow_activities USING btree (created_at);
CREATE INDEX idx_follow_activities_target ON public.follow_activities USING btree (target_id);
CREATE INDEX idx_follow_activities_type ON public.follow_activities USING btree (activity_type);
CREATE UNIQUE INDEX fraud_detection_logs_pkey ON public.fraud_detection_logs USING btree (id);
CREATE INDEX idx_fraud_detection_logs_anomalous ON public.fraud_detection_logs USING btree (is_anomalous);
CREATE INDEX idx_fraud_detection_logs_created_at ON public.fraud_detection_logs USING btree (created_at);
CREATE INDEX idx_fraud_detection_logs_risk_score ON public.fraud_detection_logs USING btree (risk_score);
CREATE INDEX idx_fraud_detection_logs_user_id ON public.fraud_detection_logs USING btree (user_id);
CREATE INDEX idx_fraud_detection_logs_user_time ON public.fraud_detection_logs USING btree (user_id, created_at);
CREATE INDEX idx_inspiration_usage_records_request_id ON public.inspiration_usage_records USING btree (request_id);
CREATE INDEX idx_inspiration_usage_records_user_id ON public.inspiration_usage_records USING btree (user_id);
CREATE UNIQUE INDEX inspiration_usage_records_pkey ON public.inspiration_usage_records USING btree (id);
CREATE INDEX idx_usage_logs_action ON public.letter_code_usage_logs USING btree (action);
CREATE INDEX idx_usage_logs_batch_id ON public.letter_code_usage_logs USING btree (batch_id);
CREATE INDEX idx_usage_logs_created_at ON public.letter_code_usage_logs USING btree (created_at);
CREATE INDEX idx_usage_logs_letter_code_id ON public.letter_code_usage_logs USING btree (letter_code_id);
CREATE UNIQUE INDEX letter_code_usage_logs_pkey ON public.letter_code_usage_logs USING btree (id);
CREATE INDEX idx_letter_codes_bound_delivered ON public.letter_codes USING btree (bound_at, delivered_at) WHERE (bound_at IS NOT NULL);
CREATE UNIQUE INDEX idx_letter_codes_code ON public.letter_codes USING btree (code);
CREATE INDEX idx_letter_codes_envelope_id ON public.letter_codes USING btree (envelope_id);
CREATE INDEX idx_letter_codes_envelope_status ON public.letter_codes USING btree (envelope_id, status) WHERE ((envelope_id)::text <> ''::text);
CREATE UNIQUE INDEX idx_letter_codes_letter_id ON public.letter_codes USING btree (letter_id);
CREATE INDEX idx_letter_codes_recipient_code ON public.letter_codes USING btree (recipient_code);
CREATE INDEX idx_letter_codes_recipient_code_status ON public.letter_codes USING btree (recipient_code, status) WHERE ((recipient_code)::text <> ''::text);
CREATE INDEX idx_letter_codes_scanned_by_time ON public.letter_codes USING btree (last_scanned_by, last_scanned_at DESC) WHERE ((last_scanned_by)::text <> ''::text);
CREATE INDEX idx_letter_codes_status ON public.letter_codes USING btree (status);
CREATE INDEX idx_letter_codes_status_updated ON public.letter_codes USING btree (status, updated_at DESC);
CREATE UNIQUE INDEX letter_codes_pkey ON public.letter_codes USING btree (id);
CREATE INDEX idx_letter_likes_letter_created ON public.letter_likes USING btree (letter_id, created_at DESC);
CREATE INDEX idx_letter_likes_letter_id ON public.letter_likes USING btree (letter_id);
CREATE INDEX idx_letter_likes_user_created ON public.letter_likes USING btree (user_id, created_at DESC);
CREATE INDEX idx_letter_likes_user_id ON public.letter_likes USING btree (user_id);
CREATE UNIQUE INDEX letter_likes_pkey ON public.letter_likes USING btree (id);
CREATE INDEX idx_letter_photos_letter_id ON public.letter_photos USING btree (letter_id);
CREATE UNIQUE INDEX letter_photos_pkey ON public.letter_photos USING btree (id);
CREATE INDEX idx_letter_replies_author_id ON public.letter_replies USING btree (author_id);
CREATE UNIQUE INDEX idx_letter_replies_delivery_code ON public.letter_replies USING btree (delivery_code);
CREATE INDEX idx_letter_replies_reply_to_letter ON public.letter_replies USING btree (reply_to_letter);
CREATE INDEX idx_letter_replies_thread_id ON public.letter_replies USING btree (thread_id);
CREATE UNIQUE INDEX letter_replies_pkey ON public.letter_replies USING btree (id);
CREATE INDEX idx_letter_shares_letter_id ON public.letter_shares USING btree (letter_id);
CREATE INDEX idx_letter_shares_platform_created ON public.letter_shares USING btree (platform, created_at DESC);
CREATE INDEX idx_letter_shares_user_id ON public.letter_shares USING btree (user_id);
CREATE UNIQUE INDEX letter_shares_pkey ON public.letter_shares USING btree (id);
CREATE INDEX idx_letter_templates_created_by ON public.letter_templates USING btree (created_by);
CREATE UNIQUE INDEX letter_templates_pkey ON public.letter_templates USING btree (id);
CREATE INDEX idx_letter_threads_last_reply_at ON public.letter_threads USING btree (last_reply_at);
CREATE INDEX idx_letter_threads_original_letter ON public.letter_threads USING btree (original_letter);
CREATE UNIQUE INDEX letter_threads_pkey ON public.letter_threads USING btree (id);
CREATE INDEX idx_letters_active_drafts ON public.letters USING btree (user_id, updated_at DESC) WHERE (((status)::text = 'draft'::text) AND (deleted_at IS NULL));
CREATE INDEX idx_letters_author_id ON public.letters USING btree (author_id);
CREATE INDEX idx_letters_complex_search ON public.letters USING btree (user_id, status, visibility, created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX idx_letters_courier_id ON public.letters USING btree (courier_id);
CREATE INDEX idx_letters_deleted_at ON public.letters USING btree (deleted_at);
CREATE INDEX idx_letters_envelope_id ON public.letters USING btree (envelope_id);
CREATE INDEX idx_letters_in_transit ON public.letters USING btree (recipient_op_code, updated_at DESC) WHERE ((status)::text = ANY ((ARRAY['collected'::character varying, 'in_transit'::character varying])::text[]));
CREATE INDEX idx_letters_recipient_id ON public.letters USING btree (recipient_id);
CREATE INDEX idx_letters_recipient_op_code ON public.letters USING btree (recipient_op_code);
CREATE INDEX idx_letters_recipient_opcode_status ON public.letters USING btree (recipient_op_code, status) WHERE ((recipient_op_code)::text <> ''::text);
CREATE INDEX idx_letters_reply_to ON public.letters USING btree (reply_to);
CREATE INDEX idx_letters_reply_to_created ON public.letters USING btree (reply_to, created_at DESC) WHERE ((reply_to)::text <> ''::text);
CREATE INDEX idx_letters_scheduled_at ON public.letters USING btree (scheduled_at);
CREATE INDEX idx_letters_sender_op_code ON public.letters USING btree (sender_op_code);
CREATE INDEX idx_letters_sender_opcode_created ON public.letters USING btree (sender_op_code, created_at DESC) WHERE ((sender_op_code)::text <> ''::text);
CREATE INDEX idx_letters_type_visibility_created ON public.letters USING btree (type, visibility, created_at DESC);
CREATE INDEX idx_letters_user_id ON public.letters USING btree (user_id);
CREATE INDEX idx_letters_user_status_created ON public.letters USING btree (user_id, status, created_at DESC);
CREATE UNIQUE INDEX letters_pkey ON public.letters USING btree (id);
CREATE INDEX idx_level_upgrade_requests_courier_id ON public.level_upgrade_requests USING btree (courier_id);
CREATE INDEX idx_level_upgrade_requests_courier_status ON public.level_upgrade_requests USING btree (courier_id, status, created_at DESC);
CREATE INDEX idx_level_upgrade_requests_level_transition ON public.level_upgrade_requests USING btree (current_level, request_level, status);
CREATE INDEX idx_level_upgrade_requests_reviewer_reviewed ON public.level_upgrade_requests USING btree (reviewed_by, reviewed_at DESC) WHERE ((reviewed_by)::text <> ''::text);
CREATE UNIQUE INDEX level_upgrade_requests_pkey ON public.level_upgrade_requests USING btree (id);
CREATE INDEX idx_moderation_queues_record_id ON public.moderation_queues USING btree (record_id);
CREATE UNIQUE INDEX moderation_queues_pkey ON public.moderation_queues USING btree (id);
CREATE INDEX idx_moderation_records_content_id ON public.moderation_records USING btree (content_id);
CREATE INDEX idx_moderation_records_content_type ON public.moderation_records USING btree (content_type);
CREATE INDEX idx_moderation_records_user_id ON public.moderation_records USING btree (user_id);
CREATE UNIQUE INDEX moderation_records_pkey ON public.moderation_records USING btree (id);
CREATE UNIQUE INDEX moderation_rules_pkey ON public.moderation_rules USING btree (id);
CREATE INDEX idx_moderation_stats_date ON public.moderation_stats USING btree (date);
CREATE UNIQUE INDEX moderation_stats_pkey ON public.moderation_stats USING btree (id);
CREATE UNIQUE INDEX museum_collections_pkey ON public.museum_collections USING btree (id);
CREATE UNIQUE INDEX museum_entries_pkey ON public.museum_entries USING btree (id);
CREATE UNIQUE INDEX museum_exhibition_entries_pkey ON public.museum_exhibition_entries USING btree (id);
CREATE UNIQUE INDEX museum_exhibitions_pkey ON public.museum_exhibitions USING btree (id);
CREATE INDEX idx_museum_interactions_entry_id ON public.museum_interactions USING btree (entry_id);
CREATE INDEX idx_museum_interactions_user_id ON public.museum_interactions USING btree (user_id);
CREATE UNIQUE INDEX museum_interactions_pkey ON public.museum_interactions USING btree (id);
CREATE INDEX idx_museum_items_origin_op_code ON public.museum_items USING btree (origin_op_code);
CREATE UNIQUE INDEX museum_items_pkey ON public.museum_items USING btree (id);
CREATE INDEX idx_museum_reactions_entry_id ON public.museum_reactions USING btree (entry_id);
CREATE INDEX idx_museum_reactions_user_id ON public.museum_reactions USING btree (user_id);
CREATE UNIQUE INDEX museum_reactions_pkey ON public.museum_reactions USING btree (id);
CREATE UNIQUE INDEX museum_submissions_pkey ON public.museum_submissions USING btree (id);
CREATE UNIQUE INDEX idx_museum_tags_name ON public.museum_tags USING btree (name);
CREATE UNIQUE INDEX museum_tags_pkey ON public.museum_tags USING btree (id);
CREATE INDEX idx_mv_barcode_status_flow_transition ON public.mv_barcode_status_flow USING btree (old_status, new_status);
CREATE UNIQUE INDEX idx_mv_courier_performance_id ON public.mv_courier_performance USING btree (courier_id);
CREATE INDEX idx_mv_courier_performance_level ON public.mv_courier_performance USING btree (level, completed_tasks DESC);
CREATE UNIQUE INDEX notification_batches_pkey ON public.notification_batches USING btree (id);
CREATE UNIQUE INDEX idx_notification_preferences_user_id ON public.notification_preferences USING btree (user_id);
CREATE UNIQUE INDEX notification_preferences_pkey ON public.notification_preferences USING btree (id);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
CREATE INDEX idx_op_code_areas_managed_by ON public.op_code_areas USING btree (managed_by) WHERE ((managed_by)::text <> ''::text);
CREATE INDEX idx_op_code_areas_school_code_active ON public.op_code_areas USING btree (school_code, area_code, is_active);
CREATE UNIQUE INDEX op_code_areas_pkey ON public.op_code_areas USING btree (id);
CREATE UNIQUE INDEX op_code_areas_school_code_area_code_key ON public.op_code_areas USING btree (school_code, area_code);
CREATE INDEX idx_op_code_schools_code_active ON public.op_code_schools USING btree (school_code, is_active);
CREATE INDEX idx_op_code_schools_managed_by ON public.op_code_schools USING btree (managed_by) WHERE ((managed_by)::text <> ''::text);
CREATE UNIQUE INDEX op_code_schools_pkey ON public.op_code_schools USING btree (id);
CREATE UNIQUE INDEX op_code_schools_school_code_key ON public.op_code_schools USING btree (school_code);
CREATE INDEX idx_order_items_order_id ON public.order_items USING btree (order_id);
CREATE INDEX idx_order_items_product_id ON public.order_items USING btree (product_id);
CREATE UNIQUE INDEX order_items_pkey ON public.order_items USING btree (id);
CREATE INDEX idx_orders_user_id ON public.orders USING btree (user_id);
CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);
CREATE UNIQUE INDEX uni_orders_order_no ON public.orders USING btree (order_no);
CREATE UNIQUE INDEX performance_alerts_pkey ON public.performance_alerts USING btree (id);
CREATE INDEX idx_performance_metrics_endpoint ON public.performance_metrics USING btree (endpoint);
CREATE INDEX idx_performance_metrics_session_id ON public.performance_metrics USING btree (session_id);
CREATE INDEX idx_performance_metrics_timestamp ON public.performance_metrics USING btree ("timestamp");
CREATE INDEX idx_performance_metrics_user_id ON public.performance_metrics USING btree (user_id);
CREATE UNIQUE INDEX performance_metrics_pkey ON public.performance_metrics USING btree (id);
CREATE INDEX idx_postal_code_applications_user_id ON public.postal_code_applications USING btree (user_id);
CREATE UNIQUE INDEX postal_code_applications_pkey ON public.postal_code_applications USING btree (id);
CREATE INDEX idx_postal_code_assignments_user_id ON public.postal_code_assignments USING btree (user_id);
CREATE UNIQUE INDEX postal_code_assignments_pkey ON public.postal_code_assignments USING btree (id);
CREATE UNIQUE INDEX uni_postal_code_assignments_postal_code ON public.postal_code_assignments USING btree (postal_code);
CREATE UNIQUE INDEX postal_code_rules_pkey ON public.postal_code_rules USING btree (id);
CREATE UNIQUE INDEX uni_postal_code_rules_school_id ON public.postal_code_rules USING btree (school_id);
CREATE UNIQUE INDEX postal_code_zones_pkey ON public.postal_code_zones USING btree (id);
CREATE UNIQUE INDEX uni_postal_code_zones_zone_id ON public.postal_code_zones USING btree (zone_id);
CREATE INDEX idx_postcode_schools_city ON public.postcode_schools USING btree (city);
CREATE UNIQUE INDEX idx_postcode_schools_code ON public.postcode_schools USING btree (code);
CREATE INDEX idx_postcode_schools_name ON public.postcode_schools USING btree (name);
CREATE INDEX idx_postcode_schools_status ON public.postcode_schools USING btree (status);
CREATE UNIQUE INDEX postcode_schools_pkey ON public.postcode_schools USING btree (id);
CREATE INDEX idx_privacy_audit_logs_action ON public.privacy_audit_logs USING btree (action);
CREATE INDEX idx_privacy_audit_logs_created_at ON public.privacy_audit_logs USING btree (created_at);
CREATE INDEX idx_privacy_audit_logs_target_user_id ON public.privacy_audit_logs USING btree (target_user_id);
CREATE INDEX idx_privacy_audit_logs_user_id ON public.privacy_audit_logs USING btree (user_id);
CREATE UNIQUE INDEX privacy_audit_logs_pkey ON public.privacy_audit_logs USING btree (id);
CREATE INDEX idx_privacy_cache_expires_at ON public.privacy_cache USING btree (expires_at);
CREATE INDEX idx_privacy_cache_viewer_target ON public.privacy_cache USING btree (viewer_user_id, target_user_id);
CREATE UNIQUE INDEX privacy_cache_pkey ON public.privacy_cache USING btree (id);
CREATE UNIQUE INDEX privacy_cache_viewer_user_id_target_user_id_key ON public.privacy_cache USING btree (viewer_user_id, target_user_id);
CREATE INDEX idx_privacy_settings_updated_at ON public.privacy_settings USING btree (updated_at);
CREATE INDEX idx_privacy_settings_user_id ON public.privacy_settings USING btree (user_id);
CREATE UNIQUE INDEX privacy_settings_pkey ON public.privacy_settings USING btree (id);
CREATE UNIQUE INDEX privacy_settings_user_id_key ON public.privacy_settings USING btree (user_id);
CREATE INDEX idx_product_favorites_product_id ON public.product_favorites USING btree (product_id);
CREATE INDEX idx_product_favorites_user_id ON public.product_favorites USING btree (user_id);
CREATE UNIQUE INDEX product_favorites_pkey ON public.product_favorites USING btree (id);
CREATE INDEX idx_product_reviews_order_id ON public.product_reviews USING btree (order_id);
CREATE INDEX idx_product_reviews_product_id ON public.product_reviews USING btree (product_id);
CREATE INDEX idx_product_reviews_user_id ON public.product_reviews USING btree (user_id);
CREATE UNIQUE INDEX product_reviews_pkey ON public.product_reviews USING btree (id);
CREATE INDEX idx_products_deleted_at ON public.products USING btree (deleted_at);
CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);
CREATE INDEX idx_scan_events_barcode_id ON public.scan_events USING btree (barcode_id);
CREATE INDEX idx_scan_events_barcode_timestamp ON public.scan_events USING btree (barcode_id, "timestamp" DESC);
CREATE INDEX idx_scan_events_deleted_at ON public.scan_events USING btree (deleted_at);
CREATE INDEX idx_scan_events_letter_code_id ON public.scan_events USING btree (letter_code_id);
CREATE INDEX idx_scan_events_lettercode_timestamp ON public.scan_events USING btree (letter_code_id, "timestamp" DESC);
CREATE INDEX idx_scan_events_location_time ON public.scan_events USING btree (location, "timestamp" DESC) WHERE ((location)::text <> ''::text);
CREATE INDEX idx_scan_events_op_code ON public.scan_events USING btree (op_code);
CREATE INDEX idx_scan_events_opcode_type_time ON public.scan_events USING btree (op_code, scan_type, "timestamp" DESC) WHERE ((op_code)::text <> ''::text);
CREATE INDEX idx_scan_events_scanned_by ON public.scan_events USING btree (scanned_by);
CREATE INDEX idx_scan_events_scanner_type_time ON public.scan_events USING btree (scanned_by, scan_type, "timestamp" DESC);
CREATE INDEX idx_scan_events_status_transition ON public.scan_events USING btree (old_status, new_status, "timestamp" DESC);
CREATE INDEX idx_scan_events_timestamp ON public.scan_events USING btree ("timestamp");
CREATE UNIQUE INDEX scan_events_pkey ON public.scan_events USING btree (id);
CREATE INDEX idx_scan_records_barcode_code ON public.scan_records USING btree (barcode_code);
CREATE INDEX idx_scan_records_courier_id ON public.scan_records USING btree (courier_id);
CREATE INDEX idx_scan_records_courier_timestamp ON public.scan_records USING btree (courier_id, "timestamp" DESC);
CREATE INDEX idx_scan_records_operator_op_code ON public.scan_records USING btree (operator_op_code);
CREATE INDEX idx_scan_records_recipient_op_code ON public.scan_records USING btree (recipient_op_code);
CREATE INDEX idx_scan_records_timestamp ON public.scan_records USING btree ("timestamp");
CREATE UNIQUE INDEX scan_records_pkey ON public.scan_records USING btree (id);
CREATE INDEX idx_scheduled_tasks_deleted_at ON public.scheduled_tasks USING btree (deleted_at);
CREATE UNIQUE INDEX scheduled_tasks_pkey ON public.scheduled_tasks USING btree (id);
CREATE INDEX idx_school_admins_active ON public.school_admins USING btree (is_active);
CREATE INDEX idx_school_admins_role ON public.school_admins USING btree (role);
CREATE INDEX idx_school_admins_school_id ON public.school_admins USING btree (school_id);
CREATE INDEX idx_school_admins_user_id ON public.school_admins USING btree (user_id);
CREATE UNIQUE INDEX school_admins_pkey ON public.school_admins USING btree (id);
CREATE UNIQUE INDEX school_admins_school_id_user_id_key ON public.school_admins USING btree (school_id, user_id);
CREATE INDEX idx_school_applications_applicant ON public.school_applications USING btree (applicant_id);
CREATE INDEX idx_school_applications_created ON public.school_applications USING btree (created_at DESC);
CREATE INDEX idx_school_applications_reviewer ON public.school_applications USING btree (reviewer_id);
CREATE INDEX idx_school_applications_status ON public.school_applications USING btree (status);
CREATE UNIQUE INDEX school_applications_pkey ON public.school_applications USING btree (id);
CREATE INDEX idx_school_departments_active ON public.school_departments USING btree (is_active);
CREATE INDEX idx_school_departments_code ON public.school_departments USING btree (code);
CREATE INDEX idx_school_departments_parent ON public.school_departments USING btree (parent_id);
CREATE INDEX idx_school_departments_school_id ON public.school_departments USING btree (school_id);
CREATE UNIQUE INDEX school_departments_pkey ON public.school_departments USING btree (id);
CREATE UNIQUE INDEX school_departments_school_id_code_key ON public.school_departments USING btree (school_id, code);
CREATE INDEX idx_school_settings_key ON public.school_settings USING btree (setting_key);
CREATE INDEX idx_school_settings_public ON public.school_settings USING btree (is_public);
CREATE INDEX idx_school_settings_school_id ON public.school_settings USING btree (school_id);
CREATE UNIQUE INDEX school_settings_pkey ON public.school_settings USING btree (id);
CREATE UNIQUE INDEX school_settings_school_id_setting_key_key ON public.school_settings USING btree (school_id, setting_key);
CREATE INDEX idx_schools_active_province ON public.schools USING btree (status, province) WHERE ((status)::text = 'active'::text);
CREATE INDEX idx_schools_code ON public.schools USING btree (code);
CREATE INDEX idx_schools_coordinates ON public.schools USING gist (coordinates);
CREATE INDEX idx_schools_created_at ON public.schools USING btree (created_at DESC);
CREATE INDEX idx_schools_level ON public.schools USING btree (school_level);
CREATE INDEX idx_schools_name ON public.schools USING btree (name);
CREATE INDEX idx_schools_name_search ON public.schools USING gin (to_tsvector('simple'::regconfig, (((((name)::text || ' '::text) || (full_name)::text) || ' '::text) || (english_name)::text)));
CREATE INDEX idx_schools_province_city ON public.schools USING btree (province, city);
CREATE INDEX idx_schools_status ON public.schools USING btree (status);
CREATE INDEX idx_schools_type ON public.schools USING btree (school_type);
CREATE INDEX idx_schools_type_level ON public.schools USING btree (school_type, school_level);
CREATE INDEX idx_schools_verification ON public.schools USING btree (verification_status);
CREATE UNIQUE INDEX schools_code_key ON public.schools USING btree (code);
CREATE UNIQUE INDEX schools_pkey ON public.schools USING btree (id);
CREATE UNIQUE INDEX idx_sensitive_words_word ON public.sensitive_words USING btree (word);
CREATE UNIQUE INDEX sensitive_words_pkey ON public.sensitive_words USING btree (id);
CREATE INDEX idx_signal_code_batches_area_id ON public.signal_code_batches USING btree (area_id);
CREATE INDEX idx_signal_code_batches_school_id ON public.signal_code_batches USING btree (school_id);
CREATE UNIQUE INDEX signal_code_batches_pkey ON public.signal_code_batches USING btree (id);
CREATE UNIQUE INDEX uni_signal_code_batches_batch_no ON public.signal_code_batches USING btree (batch_no);
CREATE INDEX idx_signal_code_rules_school_id ON public.signal_code_rules USING btree (school_id);
CREATE UNIQUE INDEX signal_code_rules_pkey ON public.signal_code_rules USING btree (id);
CREATE UNIQUE INDEX uni_signal_code_rules_rule_name ON public.signal_code_rules USING btree (rule_name);
CREATE INDEX idx_signal_code_usage_logs_code ON public.signal_code_usage_logs USING btree (code);
CREATE INDEX idx_signal_code_usage_logs_user_id ON public.signal_code_usage_logs USING btree (user_id);
CREATE UNIQUE INDEX signal_code_usage_logs_pkey ON public.signal_code_usage_logs USING btree (id);
CREATE INDEX idx_signal_codes_area_code ON public.signal_codes USING btree (area_code);
CREATE INDEX idx_signal_codes_area_id ON public.signal_codes USING btree (area_id);
CREATE INDEX idx_signal_codes_code_type ON public.signal_codes USING btree (code_type);
CREATE INDEX idx_signal_codes_is_active ON public.signal_codes USING btree (is_active);
CREATE INDEX idx_signal_codes_is_used ON public.signal_codes USING btree (is_used);
CREATE INDEX idx_signal_codes_school_code ON public.signal_codes USING btree (school_code);
CREATE INDEX idx_signal_codes_school_id ON public.signal_codes USING btree (school_id);
CREATE INDEX idx_signal_codes_zone_code ON public.signal_codes USING btree (zone_code);
CREATE UNIQUE INDEX signal_codes_pkey ON public.signal_codes USING btree (id);
CREATE UNIQUE INDEX uni_signal_codes_code ON public.signal_codes USING btree (code);
CREATE INDEX idx_status_logs_letter_id ON public.status_logs USING btree (letter_id);
CREATE INDEX idx_status_logs_letter_status_created ON public.status_logs USING btree (letter_id, status, created_at DESC);
CREATE INDEX idx_status_logs_updated_by_created ON public.status_logs USING btree (updated_by, created_at DESC) WHERE ((updated_by)::text <> ''::text);
CREATE UNIQUE INDEX status_logs_pkey ON public.status_logs USING btree (id);
CREATE INDEX idx_storage_configs_deleted_at ON public.storage_configs USING btree (deleted_at);
CREATE UNIQUE INDEX storage_configs_pkey ON public.storage_configs USING btree (id);
CREATE UNIQUE INDEX uni_storage_configs_provider ON public.storage_configs USING btree (provider);
CREATE INDEX idx_storage_files_deleted_at ON public.storage_files USING btree (deleted_at);
CREATE INDEX idx_storage_files_related_id ON public.storage_files USING btree (related_id);
CREATE INDEX idx_storage_files_uploaded_by ON public.storage_files USING btree (uploaded_by);
CREATE UNIQUE INDEX storage_files_pkey ON public.storage_files USING btree (id);
CREATE INDEX idx_storage_operations_file_id ON public.storage_operations USING btree (file_id);
CREATE INDEX idx_storage_operations_user_id ON public.storage_operations USING btree (user_id);
CREATE UNIQUE INDEX storage_operations_pkey ON public.storage_operations USING btree (id);
CREATE UNIQUE INDEX idx_system_analytics_date ON public.system_analytics USING btree (date);
CREATE UNIQUE INDEX system_analytics_pkey ON public.system_analytics USING btree (id);
CREATE INDEX idx_system_settings_category ON public.system_settings USING btree (category);
CREATE UNIQUE INDEX idx_system_settings_key ON public.system_settings USING btree (key);
CREATE UNIQUE INDEX system_settings_pkey ON public.system_settings USING btree (id);
CREATE INDEX idx_task_assignment_histories_assigned_by ON public.task_assignment_histories USING btree (assigned_by);
CREATE INDEX idx_task_assignment_histories_assigned_courier_id ON public.task_assignment_histories USING btree (assigned_courier_id);
CREATE INDEX idx_task_assignment_histories_task_id ON public.task_assignment_histories USING btree (task_id);
CREATE UNIQUE INDEX task_assignment_histories_pkey ON public.task_assignment_histories USING btree (id);
CREATE INDEX idx_task_executions_task_id ON public.task_executions USING btree (task_id);
CREATE UNIQUE INDEX task_executions_pkey ON public.task_executions USING btree (id);
CREATE UNIQUE INDEX task_templates_pkey ON public.task_templates USING btree (id);
CREATE UNIQUE INDEX task_workers_pkey ON public.task_workers USING btree (id);
CREATE INDEX idx_tasks_delivery_op_code ON public.tasks USING btree (delivery_op_code);
CREATE INDEX idx_tasks_pickup_op_code ON public.tasks USING btree (pickup_op_code);
CREATE UNIQUE INDEX tasks_pkey ON public.tasks USING btree (id);
CREATE UNIQUE INDEX uni_tasks_task_id ON public.tasks USING btree (task_id);
CREATE UNIQUE INDEX idx_user_achievement ON public.user_achievements USING btree (code);
CREATE INDEX idx_user_achievements_code_unlocked ON public.user_achievements USING btree (code, unlocked_at DESC);
CREATE INDEX idx_user_achievements_user_category ON public.user_achievements USING btree (user_id, category, unlocked_at DESC);
CREATE INDEX idx_user_achievements_user_id ON public.user_achievements USING btree (user_id);
CREATE UNIQUE INDEX user_achievements_pkey ON public.user_achievements USING btree (id);
CREATE INDEX idx_user_analytics_date ON public.user_analytics USING btree (date);
CREATE INDEX idx_user_analytics_user_id ON public.user_analytics USING btree (user_id);
CREATE UNIQUE INDEX user_analytics_pkey ON public.user_analytics USING btree (id);
CREATE INDEX idx_user_credit_actions_action_type ON public.user_credit_actions USING btree (action_type);
CREATE INDEX idx_user_credit_actions_ip ON public.user_credit_actions USING btree (ip_address, created_at);
CREATE INDEX idx_user_credit_actions_reference ON public.user_credit_actions USING btree (reference);
CREATE INDEX idx_user_credit_actions_user_action_time ON public.user_credit_actions USING btree (user_id, action_type, created_at);
CREATE INDEX idx_user_credit_actions_user_id ON public.user_credit_actions USING btree (user_id);
CREATE INDEX idx_user_credit_actions_user_time ON public.user_credit_actions USING btree (user_id, created_at);
CREATE UNIQUE INDEX user_credit_actions_pkey ON public.user_credit_actions USING btree (id);
CREATE UNIQUE INDEX idx_user_credits_user_id ON public.user_credits USING btree (user_id);
CREATE UNIQUE INDEX user_credits_pkey ON public.user_credits USING btree (id);
CREATE INDEX idx_user_daily_usages_date ON public.user_daily_usages USING btree (date);
CREATE INDEX idx_user_daily_usages_user_id ON public.user_daily_usages USING btree (user_id);
CREATE UNIQUE INDEX user_daily_usages_pkey ON public.user_daily_usages USING btree (id);
CREATE UNIQUE INDEX user_follow_stats_pkey ON public.user_follow_stats USING btree (user_id);
CREATE UNIQUE INDEX idx_user_levels_level ON public.user_levels USING btree (level);
CREATE UNIQUE INDEX user_levels_pkey ON public.user_levels USING btree (id);
CREATE UNIQUE INDEX user_privacy_settings_pkey ON public.user_privacy_settings USING btree (user_id);
CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (user_id);
CREATE INDEX idx_user_profiles_extended_levels ON public.user_profiles_extended USING btree (writing_level, courier_level);
CREATE INDEX idx_user_profiles_extended_op_code ON public.user_profiles_extended USING btree (op_code);
CREATE INDEX idx_user_profiles_extended_opcode ON public.user_profiles_extended USING btree (op_code) WHERE ((op_code)::text <> ''::text);
CREATE UNIQUE INDEX user_profiles_extended_pkey ON public.user_profiles_extended USING btree (user_id);
CREATE INDEX idx_user_redemption_histories_last_redemption ON public.user_redemption_histories USING btree (last_redemption_at DESC);
CREATE INDEX idx_user_redemption_histories_total_redemptions ON public.user_redemption_histories USING btree (total_redemptions DESC);
CREATE UNIQUE INDEX idx_user_redemption_histories_user_id ON public.user_redemption_histories USING btree (user_id);
CREATE UNIQUE INDEX user_redemption_histories_pkey ON public.user_redemption_histories USING btree (id);
CREATE INDEX idx_user_relationships_created ON public.user_relationships USING btree (created_at);
CREATE INDEX idx_user_relationships_follower ON public.user_relationships USING btree (follower_id);
CREATE INDEX idx_user_relationships_following ON public.user_relationships USING btree (following_id);
CREATE INDEX idx_user_relationships_status ON public.user_relationships USING btree (status);
CREATE UNIQUE INDEX unique_follow_relationship ON public.user_relationships USING btree (follower_id, following_id);
CREATE UNIQUE INDEX user_relationships_pkey ON public.user_relationships USING btree (id);
CREATE INDEX idx_user_stats_active_date ON public.user_stats USING btree (last_active_date DESC) WHERE (last_active_date IS NOT NULL);
CREATE INDEX idx_user_stats_points_streak ON public.user_stats USING btree (total_points DESC, current_streak DESC);
CREATE UNIQUE INDEX user_stats_pkey ON public.user_stats USING btree (user_id);
CREATE INDEX idx_user_suggestions_score ON public.user_suggestions USING btree (score DESC);
CREATE INDEX idx_user_suggestions_suggested ON public.user_suggestions USING btree (suggested_user_id);
CREATE INDEX idx_user_suggestions_user ON public.user_suggestions USING btree (user_id);
CREATE UNIQUE INDEX unique_user_suggestion ON public.user_suggestions USING btree (user_id, suggested_user_id);
CREATE UNIQUE INDEX user_suggestions_pkey ON public.user_suggestions USING btree (id);
CREATE INDEX idx_users_created_role ON public.users USING btree (created_at DESC, role) WHERE (deleted_at IS NULL);
CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);
CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_op_code ON public.users USING btree (op_code);
CREATE INDEX idx_users_role_school_active ON public.users USING btree (role, school_code, is_active) WHERE (is_active = true);
CREATE INDEX idx_users_school_code ON public.users USING btree (school_code);
CREATE UNIQUE INDEX idx_users_username ON public.users USING btree (username);
CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);
