# OpenPenPal Kubernetes命名空间配置

apiVersion: v1
kind: Namespace
metadata:
  name: openpenpal
  labels:
    app.kubernetes.io/name: openpenpal
    app.kubernetes.io/version: "2.1.0"
    environment: production

---

# 资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: openpenpal-quota
  namespace: openpenpal
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "10"
    configmaps: "10"

---

# 网络策略
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openpenpal-network-policy
  namespace: openpenpal
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: openpenpal
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 8000
  egress:
  - {}  # 允许所有出站流量