run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - generated

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - typecheck
    - govet
    - staticcheck

linters-settings:
  errcheck:
    check-blank: false
  govet:
    enable:
      - shadow
  staticcheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: main\.go
      linters:
        - errcheck
      text: "Error return value of"