#!/bin/bash

# PostgreSQL 本地设置脚本

echo "🐘 PostgreSQL 设置指南"
echo "======================="
echo ""
echo "请选择安装方式："
echo ""
echo "1. 使用 Docker (推荐)"
echo "   docker compose up -d postgres"
echo ""
echo "2. 使用 Homebrew (macOS)"
echo "   brew install postgresql@15"
echo "   brew services start postgresql@15"
echo ""
echo "3. 手动下载安装"
echo "   访问: https://www.postgresql.org/download/"
echo ""
echo "设置完成后，创建数据库："
echo ""
echo "psql -U postgres"
echo "CREATE USER openpenpal WITH PASSWORD 'openpenpal123';"
echo "CREATE DATABASE openpenpal_dev OWNER openpenpal;"
echo "GRANT ALL PRIVILEGES ON DATABASE openpenpal_dev TO openpenpal;"
echo "\q"
echo ""
echo "测试连接："
echo "psql -h localhost -U openpenpal -d openpenpal_dev"