version: '3.8'

services:
  # Prometheus时序数据库
  prometheus:
    image: prom/prometheus:latest
    container_name: openpenpal-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - openpenpal-monitoring

  # Grafana可视化
  grafana:
    image: grafana/grafana:latest
    container_name: openpenpal-grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - openpenpal-monitoring

  # AlertManager告警管理
  alertmanager:
    image: prom/alertmanager:latest
    container_name: openpenpal-alertmanager
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - ./config/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    networks:
      - openpenpal-monitoring

  # Node Exporter系统监控
  node-exporter:
    image: prom/node-exporter:latest
    container_name: openpenpal-node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - openpenpal-monitoring

  # Loki日志聚合
  loki:
    image: grafana/loki:latest
    container_name: openpenpal-loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - openpenpal-monitoring

  # Promtail日志收集
  promtail:
    image: grafana/promtail:latest
    container_name: openpenpal-promtail
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/openpenpal
      - ./config/log-monitoring.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - openpenpal-monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  openpenpal-monitoring:
    driver: bridge
